import './globals.css'
import {Locale} from "../../../i18n.config";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
  params: { lang: Locale }
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
