import './globals.css'
import {Locale} from "../../../i18n.config";
import {getDictionary} from "@/api/dictionary";
import NavBar from "@/components/NavBar/NavBar";

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default async function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
    params: { lang: Locale }
}) {
    const {navigation} = await getDictionary(params.lang)

    return (
        <html lang="en">
        <NavBar navigation={navigation}/>
        <body>{children}</body>
        </html>
    )
}
